### ISSUE TITLE
Wrong status code for Centrifugo response

### ISSUE THREAD

**Issue by vadimbalakhanov** [fre5h/CentrifugoBundle#25]
Hello two days ago we started to get 'Wrong status code for Centrifugo response' error.

bundle version - 1.4.0
centrifugo version  - 2.8

I just would like to ask is that known issue and may be you know the steps how to solve it and which way to move. Strange thing that all had being working till Wednesday (March, 16 2022)

If the issue is not spread may be you just give us any suggestions.

Thank you a lot for advance!

**Comment by fre5h** [comment]
Hi. Bundle is only wrapper over the Centrifugo server. So it is something wrong with Centrifugo. Unfortunately have no idea. Do you get this error always? Or only sometimes? Have you tried to restart Centrifugo server? Maybe somebody has updated some configs of Centrifugo?

**Comment by vadimbalakhanov** [comment]
The error happens mostly every time but not permanently. 
Restart did not help unfortunately.
Nobody changed anything with config. 

Anyway thank you a lot for your advises! 

I am going to dive into it more.
