### ISSUE TITLE
Add Meta to JWT token 

### ISSUE THREAD

**Issue by SaintMaximov** [fre5h/CentrifugoBundle#40]
Hello ! Could you please add the ability to transfer Meta when generating a JWT token?

As an option, add the `getCentrifugoMetaInfo()` interface

Required to work with [proxy](https://centrifugal.dev/docs/server/authentication#meta) to backend

Thanks

**Comment by fre5h** [comment]
@maxandwell Hi. Please point the link to the docs where this is described. And I will add it

**Comment by SaintMaximov** [comment]
I attached the link above, I’ll duplicate it again - https://centrifugal.dev/docs/server/authentication#meta and https://centrifugal.dev/docs/server/authentication#meta

Thanks!

**Comment by fre5h** [comment]
@maxandwell please check `5.3.0`
