### ISSUE TITLE
DateTimeHelper

### ISSUE THREAD

**Issue by andrconstruction** [fre5h/CentrifugoBundle#9]
I faced with an error

Cannot autowire service "Fresh\CentrifugoBundle\Service\Credentials\CredentialsGenerator": argument "$dateTimeHelper" of method "__construct()" references class "Fresh\DateTime\DateTimeHelper" but no such service exists.

a class exists, example copied from documentation, what do I do wrong?

Symfony 5.1

**Comment by andrconstruction** [comment]
Solved by manual register the DateTimeHelper within services.yaml

**Comment by fre5h** [comment]
It is a bug. Class DateTimeHelper should be registered in CentrifugoBundle. I will fix it.
Thanks for reporting

**Comment by andrconstruction** [comment]
Thanks

**Comment by fre5h** [comment]
Check release 1.2.1
